name: hearts_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=9.8.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - krb5=1.21.3
  - libcxx=20.1.8
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pip=25.3
  - platformdirs=4.5.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - readline=8.3
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - accelerate==1.1.1
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.8
      - aiosignal==1.3.1
      - alembic==1.17.2
      - altair==6.0.0
      - annotated-types==0.7.0
      - anyio==4.6.2.post1
      - arrow==1.3.0
      - attrs==24.2.0
      - blinker==1.9.0
      - blis==1.0.1
      - cachetools==6.2.2
      - catalogue==2.0.10
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==3.1.0
      - codecarbon==2.8.0
      - colorama==0.4.6
      - colorlog==6.10.1
      - confection==0.1.5
      - contourpy==1.3.1
      - cryptography==44.0.0
      - cycler==0.12.1
      - cymem==2.0.10
      - datasets==3.1.0
      - dill==0.3.8
      - en-core-web-lg==3.8.0
      - fief-client==0.20.0
      - filelock==3.16.1
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.26.3
      - idna==3.10
      - imageio==2.36.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jwcrypto==1.5.6
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - lime==0.2.0.1
      - llvmlite==0.43.0
      - logging==0.4.9.6
      - mako==1.3.10
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.11
      - narwhals==2.13.0
      - networkx==3.4.2
      - nltk==3.9.2
      - numba==0.60.0
      - numpy==2.0.2
      - optuna==4.6.0
      - packaging==24.2
      - pandas==2.2.3
      - patsy==1.0.2
      - pillow==11.0.0
      - preshed==3.0.9
      - prometheus-client==0.21.0
      - prompt-toolkit==3.0.36
      - propcache==0.2.0
      - protobuf==6.33.1
      - psutil==6.1.0
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pycparser==2.22
      - pydantic==2.10.2
      - pydantic-core==2.27.1
      - pydeck==0.9.1
      - pygments==2.18.0
      - pynvml==11.5.3
      - pyparsing==3.2.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - questionary==2.0.1
      - rapidfuzz==3.10.1
      - referencing==0.37.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.30.0
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.6.0rc1
      - scipy==1.14.1
      - seaborn==0.13.2
      - setuptools==75.6.0
      - shap==0.46.0
      - shellingham==1.5.4
      - six==1.16.0
      - slicer==0.0.8
      - smart-open==6.4.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.8.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.45
      - srsly==2.4.8
      - statsmodels==0.14.6
      - streamlit==1.52.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - termcolor==2.3.0
      - thinc==8.3.2
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tokenizers==0.20.3
      - toml==0.10.2
      - torch==2.5.1
      - torchvision==0.20.1
      - tqdm==4.67.1
      - transformers==4.46.3
      - typer==0.9.4
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wasabi==1.1.3
      - wcwidth==0.2.13
      - weasel==0.3.4
      - wordcloud==1.9.4
      - xxhash==3.5.0
      - yarl==1.18.0
      - yaspin==3.1.0
prefix: /opt/anaconda3/envs/hearts_env
